### PR TITLE
Improve performance of Color.js benchmark

### PR DESCRIPTION
**Pull request by lloydk**
Changes the benchmark to use the Color.js function oriented interface and tries to ensure that the benchmark is comparing equivalent amounts of work.

The Color.js generic matrix multiplication function is extremely slow so I think that may get changed in a future release.

### CODE REVIEW

**Comment by mattdesl** [comment]
Thanks for the PR!

The purpose of the benchmark is to compare "out of the box performance" in a standard application of the library; i.e. what is the entry-point for each library. I don't feel it makes sense to change the original benchmark to something so contrived. 

However, I can add a second benchmark that compares @texel/color against a procedural usage of Colorjs, like this:

```js
import { OKLCH, sRGB } from "colorjs.io/fn";
const out = sRGB.from(OKLCH, [0.5, 0.2, 0.7]);
```

Interestingly this is still quite slow for Colorjs, and @texel/color provides about the same speedup as I saw in my original benchmark. Any idea why?

```
OKLCH to sRGB conversion --
Colorjs: 340.10 ms
Ours: 13.25 ms
Speedup: 25.7x faster
```

**Comment by lloydk** [comment]
> 
> The purpose of the benchmark is to compare "out of the box performance" in a standard application of the library; i.e. what is the entry-point for each library. I don't feel it makes sense to change the original benchmark to something so contrived.
> 

I would argue that the current benchmark is contrived because you're benchmarking against an api that wasn't designed for performance and ignoring functions that are provided out of the box that would increase performance. From the [Color.js docs](https://colorjs.io/docs/procedural)

> In addition to the object oriented API that most examples here use, Color.js also supports a procedural API that operates on plain objects instead of Color objects.
>
> There are several reasons to use this API:
>
> - It is approximately two times faster, **making it more suitable for performance-sensitive tasks**.

Color.js is never going to be the fasted library but I do think that because this library is focused on performance that the benchmark should use Color.js in a more performant manner.


> 
> Interestingly this is still quite slow for Colorjs, and @texel/color provides about the same speedup as I saw in my original benchmark. Any idea why?
> 
> ```
> OKLCH to sRGB conversion --
> Colorjs: 340.10 ms
> Ours: 13.25 ms
> Speedup: 25.7x faster
> ```

I'll take a look later today but I suspect that because conversion performance is hampered by the generic matrix multiplication function there's little performance improvement.  I was able to get the time for the conversion benchmark in the original benchmark to around 3x slower just by replacing the matrix multiplication function with the `transform()` function from this library.

**Comment by mattdesl** [comment]
The comparison is "out of the box performance" of each API; the philosophy here is that you get the performance and bundle optimizations of all possible conversion paths 'for free' without requiring additional boilerplate or configuration.

However, I'll look into merging your code into the original benchmark, perhaps using a wrapper file around Colorjs' procedural API to keep the benchmark script itself fairly clean and easy to maintain going forward.

**Comment by lloydk** [comment]
> 
> Interestingly this is still quite slow for Colorjs, and @texel/color provides about the same speedup as I saw in my original benchmark. Any idea why?
> 
> ```
> OKLCH to sRGB conversion --
> Colorjs: 340.10 ms
> Ours: 13.25 ms
> Speedup: 25.7x faster
> ```

I might be misunderstanding what you're saying. Are you suggesting there's no speedup difference between the object oriented api and the procedural api?

When I run `test/bench-colorjs-fn.js` I get a Speedup of around 35. If I change `sRGB.from(OKLCH, vec);` to `new Color("oklch", vec).to("srgb")` I see a Speedup of around 105. So on my machine for this benchmark the procedural api is 3 time faster than the objected oriented api.


For the original colorjs benchmark I see a 10%ish improvement in the first test, 4x improvement in the second test and around 50% improvement in the third test when switching to the procedural api. The times for the first and third tests are dominated by the css gamut mapping algorithm which is quite slow.

**Comment by mattdesl** [comment]
No—I was wondering why there was such a large discrepancy between a single OKLCH conversion and a multi-conversion benchmark. It looks like I had a typo where `tmp` should have been `vec` which was causing this discrepancy:

```js
- Colors.convert(tmp, Colors.OKLCH, Colors.sRGB, tmp);
+ Colors.convert(vec, Colors.OKLCH, Colors.sRGB, tmp);
```

This has been fixed and integrated into `test/bench-colorjs.js` which compares `@texel/color` against both Colorjs APIs, and updates the output in the readme.

Thanks!

**Pull request closed without merging**
